DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
	id SERIAL,
	`table` VARCHAR(255),
	entry_id INT UNSIGNED,
	`name` VARCHAR(255),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Data logs' ENGINE = ARCHIVE;

SHOW TABLE STATUS LIKE 'logs';

DROP TRIGGER IF EXISTS insert_logs_u;
DELIMITER //
CREATE TRIGGER insert_logs_u AFTER INSERT ON users
FOR EACH ROW
BEGIN
  INSERT INTO logs VALUES (DEFAULT, 'users', NEW.id, NEW.name, DEFAULT);
END//

DROP TRIGGER IF EXISTS insert_logs_p;
DELIMITER //
CREATE TRIGGER insert_logs_p AFTER INSERT ON products
FOR EACH ROW
BEGIN
  INSERT INTO logs VALUES (DEFAULT, 'products', NEW.id, NEW.name, DEFAULT);
END//

DROP TRIGGER IF EXISTS insert_logs_c;
DELIMITER //
CREATE TRIGGER insert_logs_c AFTER INSERT ON catalogs
FOR EACH ROW
BEGIN
  INSERT INTO logs VALUES (DEFAULT, 'catalogs', NEW.id, NEW.name, DEFAULT);
END//

SELECT * FROM logs;

INSERT INTO users VALUES (DEFAULT, 'Vladi', '1996-01-01', DEFAULT, DEFAULT);